github:
  client_id: "${client_id}"

  client_secret: "${HOMEBREW_GITHUB_API_TOKEN}"
github:
  client_id: "${client_id}"
  client_secret: "${HOMEBREW_GITHUB_API_TOKEN}"
>>>>>>> master
=======
codecov:
  token: "${CODECOV_TOKEN}, ${HOMEBREW_CODECOV_TOKEN}"
  bot: "codecov-io"
  ci:
    - "travis.org"
    - "jgj-c.xyz"
=======
codecov:
  token: "${CODECOV_TOKEN}, ${HOMEBREW_CODECOV_TOKEN}"
  bot: "codecov-io"
  ci:
    - "travis.org"
<<<<<<< HEAD
>>>>>>> Create codecov.yml
=======
    - "jgj-c.xyz"
>>>>>>> brew vendor-gems: commit updates.
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
<<<<<<< HEAD
<<<<<<< HEAD
parsers:
  v1:
    include_full_missed_files: true  # default false
runs-on: self-hoste
=======
>>>>>>> Create codecov.yml
=======
parsers:
  v1:
    include_full_missed_files: true  # default false
<<<<<<< HEAD
>>>>>>> master
=======
runs-on: self-hoste
>>>>>>> brew vendor-gems: commit updates.
