codecov:
  token: "${CODECOV_TOKEN}"
  bot: "codecov-io"
  ci:
    - "travis.org"
    - "jgj-c.xyz"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
parsers:
  v1:
    include_full_missed_files: true  # default false
runs-on: self-hoste